### ISSUE TITLE
403 on screenshots with thum.io

### ISSUE THREAD

**Issue by bilyboy785** [towfiqi/serpbear#150]
Hello,

It's seem's that your thum account is frozzen : 

`This account is currently frozen. Please sign in to correct this issue.`

![](https://media.cleanshot.cloud/media/15917/EdvsM57TNbLm1vRGBEntPkASXdDdL1xhmBn5a8UP.jpeg?Expires=1705336393&Signature=M-WS3o7JARXbw3UM26HjCSxoaJFE4mOsclfCApX9UvCfp7Q4zWCiZvde~PHFLgRTlIbAi1KnTng2l9oHeNip09n4inNCksYONVX4t5oNCl4LKf8-zq5WIVZowG04FZTjrsMup0LOIZG2oWA432syzUXaJtV-~WMVNN7R-cxTyDbLzY3b9uu~bRLUPKwUD26LZRMzBoxIGKMBwu40TPEDFtD75LRRK~Sy2xquOxew9Mtrbwkx6HkaQC9fxHttd3X50jfqbLQba1dQUIXT4KA33qNzj6l1EltgJPH7~D03~JQY8Az2poKfffBOV5nGF6fWLi81Eev3Try-NAtiqYmjYQ__&Key-Pair-Id=K269JMAT9ZF4GZ)

Do you think we could use another method to get favicon / screenshot ?

**Comment by towfiqi** [comment]
The app uses a free thum.io account which has a monthly limit of 1000 thumbnail generation. Since it's used by everyone who uses SerpBear you can guess it is depleted pretty easily each month. You can create a free thum.io account and use your own API key as a `SCREENSHOT_API` environment variable. You can learn more here: https://docs.serpbear.com/miscellaneous/environment-variables
