### ISSUE TITLE
Hashtag results cut the keyword

### ISSUE THREAD

**Issue by JvB94** [towfiqi/serpbear#221]
Hi,

as soon as i add a keyword with a hashtag, e.g. “test #test”, it doesn't search for the keyword but for everything in front of it, i.e. “test”.
I have some keywords with a # so it would be great if it could be fixed.

**Comment by towfiqi** [comment]
Ok, just tested it and I cannot recreate the issue. I added the keyword “test #test” and the scraper fetched the correct keyword which includes the hash. Can you please elaborate?

**Comment by JvB94** [comment]
![image](https://github.com/user-attachments/assets/e7d0a3e0-76dd-4dc0-981d-1524a86adb37)
Maybe it's related to the api.

**Comment by towfiqi** [comment]
Looks like it. I was able to recreate the issue with Serper. 
It looks like it returns an Unauthorized error when you request a keyword with a hash in it. I have already shared this with the Serper team let's see what they say. And since the bus is on their side, I will close this issue now. Thanks for reporting.

**Comment by towfiqi** [comment]
Ok. It looks like the bug is within SerpBear and not Serper.dev. Will fix the bug in the next release.
